# Generated by Django 3.2.6 on 2022-03-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='prof',
            field=models.CharField(default=1, max_length=255, verbose_name='Профссия'),
            preserve_default=False,
        ),
    ]
