# Generated by Django 3.2.6 on 2022-04-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='главное')),
                ('text', models.IntegerField(max_length=255, verbose_name='текст')),
            ],
        ),
    ]
