# Generated by Django 3.2.6 on 2022-04-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='text',
            field=models.TextField(max_length=255, verbose_name='текст'),
        ),
    ]
