# Generated by Django 3.2.6 on 2022-04-15 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_book_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='books',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.book'),
        ),
    ]
